### ISSUE TITLE
error Cannot open the file! (3)

### ISSUE THREAD

**Issue by xuxuedong** [hasherezade/libpeconv#11] opened 2019-08-20 07:52 UTC
when i compile the run_pe with the libpeconv within the project, i always get this error, the file is exist, can you help me?

**Comment by xuxuedong** [comment] 2019-08-20 07:53
the error code is returned by i added GetLastError()

**Comment by hasherezade** [comment] 2019-08-20 15:30
can you describe more about when exactly do you get this error?
is it at compilation time? which file is missing? 
or is it when you deploy `run_pe.exe` with the paths to the target and to the payload?
please attach screenshots illustrating the problem.

**Comment by xuxuedong** [comment] 2019-08-21 10:19
i compiled the run_pe, and when i deploy run_pe.exe with the paths to the target and to the payload, it always remain me "can't open file", i try two methods to compile run_pe, first is add all the .h files and the .cpp files to the run_pe project, second is compile the libpeconv to a lib, and link it to the run_pe, but both is remain "can't open file", i added GetLastError() in suitable place in pe_loader.cpp and it return error code 3, i will attach screenshot late
发自我的 iPhone

在 2019年8月20日，23:30，@hasherezade <notifications@github.com<mailto:notifications@github.com>> 写道：

deploy run_pe.exe with the paths to the target and to the payload

**Comment by hasherezade** [comment] 2019-08-21 14:25
This is not a compilation error, it may be an error related to the access to the file, or related with fact that it uses ANSI paths.
Try to check if the normal ``CreateFileA`` can open the same file.
Compile and test this snippet and tell me what output it gives you:
https://gist.github.com/hasherezade/78747fc724e68f055630882600eecc2b#file-main-cpp

**Comment by xuxuedong** [comment] 2019-08-22 11:31
this is the screenshot before
![2019-08-22 19-01-16屏幕截图](https://user-images.githubusercontent.com/9376976/63511304-6ae5b400-c513-11e9-9cd5-86a63a31498a.png)

**Comment by xuxuedong** [comment] 2019-08-22 11:39
and when i use the snippet, it always output "OK" although the file is not exist, i don't know why, and i add a function GetFileSize in suitable place, i return -1, below is the screenshot
![2019-08-22 19-35-57屏幕截图](https://user-images.githubusercontent.com/9376976/63511565-1a228b00-c514-11e9-84df-5bd982044af6.png)

**Comment by xuxuedong** [comment] 2019-08-22 11:42
the system what i use is commando from fireeye, it is a little different from win10

**Comment by hasherezade** [comment] 2019-08-23 06:41
sorry, I forgot to add a check for attributes. please try to run the new version of the snippet: https://gist.github.com/hasherezade/78747fc724e68f055630882600eecc2b#file-main-cpp

**Comment by xuxuedong** [comment] 2019-08-23 14:08
it also always output "Can't open: .\xxx.exe : INVALID_FILE_ATTRIBUTES" whether the file exist or not, below are the screenshots
![%WVTBQ@ CK%FGCZ)5KHVXFM](https://user-images.githubusercontent.com/9376976/63598530-56c4b400-c5f2-11e9-8eb1-7e2b0ab23926.png)
![%}{XV7~F$6PAI1P1KU}_(59](https://user-images.githubusercontent.com/9376976/63598541-5a583b00-c5f2-11e9-8d4a-98e71403270b.png)
the abc.exe and the putty_x64.exe are in the same dir with the ConsoleApplication1.exe

**Comment by xuxuedong** [comment] 2019-08-23 14:12
i have adjusted the params of the CreateFileA() to the other normal form, but it also have the same output

**Comment by hasherezade** [comment] 2019-08-23 16:39
ok. Can you try a unicode version?
https://gist.github.com/hasherezade/78747fc724e68f055630882600eecc2b#file-wmain-cpp
Maybe the path encoding is the problem.

**Comment by xuxuedong** [comment] 2019-08-24 14:36
yes, it's correct this time
when the files are exist, it return
"Can't open: .\a.exe : INVALID_FILE_ATTRIBUTES
Can't open: .\b.exe : INVALID_FILE_ATTRIBUTES"
when the files are not exist, it return
"OK: ., attributes: 20
OK: .\putty_x64.exe, attributes: 20"
but the payload_path name may only be read the first character when the file is exist
below is the screen
![~09VC8@ORBHP9F75K8)T RS](https://user-images.githubusercontent.com/9376976/63638827-97d6ca00-c6bf-11e9-945d-cccadb984bfa.png)
![0}_72X3UA SO`(DPDGK5U~L](https://user-images.githubusercontent.com/9376976/63638828-99a08d80-c6bf-11e9-83c1-f9ac748583f3.png)
![XLM5RU(}A6GP PS~6@Z }W2](https://user-images.githubusercontent.com/9376976/63638831-9c02e780-c6bf-11e9-8d97-e0cb4a7620b3.png)
the current dir only have putty_x64.exe and abc.exe

**Comment by xuxuedong** [comment] 2019-08-25 08:23
i also have a problem, why the run_pe64.exe that you provided is valid, but the run_pe64.exe that i compiled is invalid, is it because my compile method?

**Comment by hasherezade** [comment] 2019-08-26 16:45
Please check if the recent patch fixed the problem.

**Comment by xuxuedong** [comment] 2019-08-27 05:01
i download the latest code, compile it, it output "Incompatibile target subsystem!" this time, the subsystem of my payload is console, and the subsystem of this loader is also console

**Comment by xuxuedong** [comment] 2019-08-27 05:04
i try to commented the below code in run_pe.cpp
if (payload_subs != IMAGE_SUBSYSTEM_WINDOWS_GUI //only a payload with GUI subsystem can be run by both GUI and CLI
        && target_subs != payload_subs)
    {
        printf("Incompatibile target subsystem!\n");
        return false;
    }
but it will popup
![2019-08-27 13-03-32屏幕截图](https://user-images.githubusercontent.com/9376976/63742355-23707680-c8cb-11e9-98ce-073fd3968d9f.png)

**Comment by xuxuedong** [comment] 2019-08-27 05:17
and those builds you did recently also output "Incompatibile target subsystem!", but once again, the original builds can work correctly

**Comment by hasherezade** [comment] 2019-08-27 05:25
You should not comment out this code! It is an important compatibility check! It is here for a valid purpose. If it passed to this stage, it means the original issue of not opening file is solved.

The "Incompatibile target subsystem!" is not a bug. It is just an info that your payload is incompatible with your target. You must use a payload with a GUI subsystem if you want to inject into a target with a GUI subsystem (such as calc). For checking a subsystem use a PE viewer such as [PE-bear](https://github.com/hasherezade/pe-bear-releases/releases).

Check the Optional Header -> Subsystem in both payload and a target (the default target is calc):
![subsystem_info](https://user-images.githubusercontent.com/3115348/63743028-35d2bc00-c89b-11e9-8fad-0a3dd1dab8fc.png)

If the subsystem of the payload is "Windows console", it just cannot be injected into target with subsystem "Windows GUI". The check that you commented out is meant to inform you about it, and prevent from further problems.

**Comment by hasherezade** [comment] 2019-08-27 05:30
In some cases, you can enforce payload to be still injected, just by changing its subsystem in the header. In the past my loader was doing it, but it was causing problems in some cases, so I removed it. If you really want to try, you can change the target's subsystem manually in the PE editor (such as PE-bear) and it should work. Just change the value from 3 to 2. But only if you are sure that you want it.
In general is better to choose a different target instead.

**Comment by hasherezade** [comment] 2019-08-27 05:37
BTW if you read the line that you commented out, you will find the same explanation as above:
```
//only a payload with GUI subsystem can be run by both GUI and CLI
```

**Comment by xuxuedong** [comment] 2019-08-27 05:48
i read the explanation, so i commented it, what i understand is "a GUI subsystem can be run by both GUI and CLI, and a CLI subsystem can only be run by CLI subsytem" :)
i was a little foolish...
Is it only the GUI subsystem can be inject to both GUI and CLI subsystem, the CLI subsystem can't be inject to either GUI or CLI subsystem?

**Comment by xuxuedong** [comment] 2019-08-27 05:51
thank you very much really for your help so far :)

**Comment by hasherezade** [comment] 2019-08-27 05:55
Unfortunately it is not transitive. Payload with with GUI subsystem has lesser limitations, and can be injected to both GUI and CLI. 
So: 
GUI payload -> GUI or CLI target
CLI payload -> CLI target (only)

**Comment by xuxuedong** [comment] 2019-08-27 05:58
i have change my payload from console to GUI, and it can be inject successfully, thank you again brother

**Comment by hasherezade** [comment] 2019-08-27 06:01
I'm glad that it worked, and thank you for reporting an issue with file opening! And input like yours is invaluable to make my tools better, so, thanks! :)

**Comment by xuxuedong** [comment] 2019-08-27 06:17
before i commented the below code
/*
if (payload_subs != IMAGE_SUBSYSTEM_WINDOWS_GUI //only a payload with GUI subsystem can be run by both GUI and CLI
&& target_subs != payload_subs)
{
printf("Incompatibile target subsystem!\n");
return false;
}
*/
and i choose svchost.exe as the target (i think it's console subsystem, because it has no GUI)
it also failed
but now i know the svchost.exe is GUI subsystem
thanks for your tool PE-bear

**Comment by xuxuedong** [comment] 2019-08-27 06:18
is there any windows utility  is console subsystem?

**Comment by hasherezade** [comment] 2019-08-27 06:21
> is there any windows utility is console subsystem?

Try: `C:\Windows\bfsvc.exe`

**Comment by hasherezade** [comment] 2019-08-27 06:25
Also:
`C:\Windows\System32\PATHPING.exe`
`C:\Windows\System32\PING.exe`
`C:\Windows\System32\print.exe`
`C:\Windows\System32\qprocess.exe`

There are some. PE-bear will help you to find more ;)

**Comment by xuxuedong** [comment] 2019-08-27 06:30
thanks a lot, my payload can be inject to c:\windows\bfsvc.exe successfully

**Comment by hasherezade** [comment] 2019-08-27 06:31
cool! so, if all is sorted out, I think it's time to close this topic.

**Closed** 2019-08-27 06:32 UTC
